image: helldar/laravel-gitlab-ci:8.0

services:
    - mysql:5.7
    - redis:latest

variables:
    APP_NAME: "${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}"
    MYSQL_DATABASE: database_name
    MYSQL_ROOT_PASSWORD: secret
    GITLAB_HOST: 123.123.123.123
    GITLAB_PORT: "22"
    PRODUCTION_HOST: 123.123.123.123


.init_ssh: &init_ssh |
    mkdir -p ~/.ssh
    chmod 700 ~/.ssh
    printf "Host $GITLAB_HOST\n\tHostname $GITLAB_HOST\n\tPort $GITLAB_PORT\n\tUser git\n\tIdentityFile ~/.ssh/id_rsa\n\n" >> ~/.ssh/config
    chmod 644 ~/.ssh/config
    echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ssh-keyscan $PRODUCTION_HOST >> ~/.ssh/known_hosts
    ssh-keyscan $GITLAB_HOST >> ~/.ssh/known_hosts
    chmod 644 ~/.ssh/known_hosts

.change_file_permissions: &change_file_permissions |
    find . -type f -not -path "./vendor/*" -exec chmod 664 {}
    find . -type d -not -path "./vendor/*" -exec chmod 775 {}

.php_version: &php_version |
    php -v


composer:
    stage: build
    only:
        - master
        - release
    cache:
        key: ${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-composer
        paths:
            - vendor/
    script:
        - *init_ssh
        - *php_version
        - composer install --prefer-dist --no-interaction --no-progress --no-scripts --no-suggest
        - cp .env.testing .env
        - php artisan key:generate -vvv
    artifacts:
        expire_in: 1 week
        paths:
            - vendor/
            - .env

yarn:
    stage: build
    only:
        - master
        - release
    cache:
        key: ${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-yarn
        paths:
            - node_modules/
    script:
        - yarn install --network-timeout=500000
        - yarn production
    artifacts:
        expire_in: 1 week
        paths:
            - node_modules/
            - public/mix-manifest.json

phpunit:
    stage: test
    only:
        - master
        - release
    dependencies:
        - composer
        - yarn
    script:
        - php artisan migrate:fresh --seed --force -vvv
        - phpunit --no-coverage -v

production:
    stage: deploy
    only:
        - release
    script:
        - *init_ssh
        - *change_file_permissions
        - php artisan deploy -vvv --revision=$CI_COMMIT_SHA
